import { Product } from "./types";

export const dummyProducts: Product[] = [
	{
		id: 1,
		price: '2.99',
		name: "Butter",
		image: "assets/images/products/butter.jpeg",
		rating: 4.2,
	},
	{
		id: 2,
		price: '2.49',
		name: "Cheese",
		image: "assets/images/products/cheese.jpeg",
		rating: 4.6,
	},
	{
		id: 3,
		price: '1.99',
		name: "Eggs",
		image: "assets/images/products/eggs.jpeg",
		rating: 4.5,
	},
	{
		id: 4,
		price: '3.99',
		name: "Ice-cream",
		image: "assets/images/products/ice-cream.jpeg",
		rating: 4.9,
	},
	{
		id: 5,
		price: '1.99',
		name: "Milk",
		image: "assets/images/products/milk.jpeg",
		rating: 5.0,
	},
	{
		id: 6,
		price: '0.49',
		name: "Yogurt",
		image: "assets/images/products/yogurt.jpeg",
		rating: 4.5,
	},
	{
		id: 7,
		price: '3.99',
		name: "Bacon",
		image: "assets/images/products/bacon.jpeg",
		rating: 4.9,
	},
	{
		id: 8,
		price: '4.99',
		name: "Beef",
		image: "assets/images/products/beef.jpeg",
		rating: 5.0,
	},
	{
		id: 9,
		price: '2.99',
		name: "Chicken Wings",
		image: "assets/images/products/chicken-wings.jpeg",
		rating: 3.8,
	},
	{
		id: 10,
		price: '1.99',
		name: "Drumsticks",
		image: "assets/images/products/drumsticks.jpeg",
		rating: 4.0,
	},
	{
		id: 11,
		price: '1.99',
		name: "Sour Cream",
		image: "assets/images/products/sour-cream.jpeg",
		rating: 4.5,
	},
];
